### PR TITLE
Fix Cedric's dumb init.vim

### LINKED ISSUE #1: Fix Cedric's ugly init.vim

### PR DESCRIPTION
**Pull request by VimFreeman**
Closes #1

### CODE REVIEW

**Review by MartensCedric — CHANGES_REQUESTED** [review]
why was incsearch removed?

**Comment by VimFreeman** [comment]
because `is` is the same thing

**Review by MartensCedric — APPROVED** [review]

**Comment by VimFreeman** [comment]
merge it

**Comment by VimFreeman** [comment]
merge it
i wanna have a pr on your repo

**Pull request merged**
